In [1]:
import numpy as np 

# Mathematical Oppearation 

In [2]:
np.sqrt([28, 56, 78,])

array([5.29150262, 7.48331477, 8.83176087])

In [3]:
np.sin([28, 56, 78,])

array([ 0.27090579, -0.521551  ,  0.51397846])

In [4]:
np.std([28, 56, 78,])

20.46134567096374

In [5]:
np.median([28, 56, 78,])

56.0

In [6]:
np.mean([28, 56, 78,])

54.0

In [7]:
Bod = np.array([2,34,5,7,8,9])

In [8]:
np.eye(5, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [9]:
np.random.randint(40, 57, 4)


array([46, 51, 53, 42])

In [10]:
np.random.seed(20)

In [11]:
np.random.rand(4, 6)

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959,
        0.69175758],
       [0.37868094, 0.51851095, 0.65795147, 0.19385022, 0.2723164 ,
        0.71860593],
       [0.78300361, 0.85032764, 0.77524489, 0.03666431, 0.11669374,
        0.7512807 ],
       [0.23921822, 0.25480601, 0.85762553, 0.94977903, 0.56168686,
        0.17878052]])

In [12]:
np.argmax((4, 6, 3, 7, 0))

3

In [13]:
np.argmin((4, 6, 3, 7, 0))

4

# INDEXING AND SELECTION 

In [14]:
f = np.array([ 2, 4, 6, 7, 8, 9, 0, 3])

In [15]:
np.arange(8).reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
f * 5

array([10, 20, 30, 35, 40, 45,  0, 15])

In [17]:
f [f > 4]

array([6, 7, 8, 9])

# PANDAS

In [18]:
import pandas as pd 

import numpy as np 

In [19]:
var = [ 2,45,7,8,9,4,56,73,25,54,567,]

In [20]:
pd.Series(var, index = ['a', 'b' , 'c' ,'d' ,'e' ,'f' , 'g' , 'h' , 'i' , 'h' , 'l'])

a      2
b     45
c      7
d      8
e      9
f      4
g     56
h     73
i     25
h     54
l    567
dtype: int64

In [21]:
pd.DataFrame(var, columns = ['a'])

a
0     2
1    45
2     7
3     8
4     9
5     4
6    56
7    73
8    25
9    54
10  567

In [22]:
slot = np.eye(10)

In [23]:
my_df = pd.DataFrame(slot, columns = ['lagos', 'eko', 'ibadan', 'kishi', 'soro', 'igbeti', 'igboho', 'pole', 'jolo', 'Agwara'],
             index = ['a', 'b' , 'c' ,'d' ,'e' ,'f' , 'g' , 'h' , 'i' , 'h' ,] )

In [24]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to h
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   lagos   10 non-null     float64
 1   eko     10 non-null     float64
 2   ibadan  10 non-null     float64
 3   kishi   10 non-null     float64
 4   soro    10 non-null     float64
 5   igbeti  10 non-null     float64
 6   igboho  10 non-null     float64
 7   pole    10 non-null     float64
 8   jolo    10 non-null     float64
 9   Agwara  10 non-null     float64
dtypes: float64(10)
memory usage: 880.0+ bytes


In [25]:
Data = pd.DataFrame ( {'Name': ['habeeb','Tajudeen','Alabi','Lola','Ojo','Ahmed', 'Bolu','Alake','Ishola','Saheed'],
         'School': ['Havard','Oxford','Alberta','Kwasu','Stanford','Cabridge','Lasu','Unilag','Unilorin','Tasued'],
        'score': ['87','67','54','45','76','100','60','48','34','58'], 
                       'Age': ['23','25','21','12','34','100','90','40','34','51']})

In [26]:
Data[['Name','School','Age']]

Name    School  Age
0    habeeb    Havard   23
1  Tajudeen    Oxford   25
2     Alabi   Alberta   21
3      Lola     Kwasu   12
4       Ojo  Stanford   34
5     Ahmed  Cabridge  100
6      Bolu      Lasu   90
7     Alake    Unilag   40
8    Ishola  Unilorin   34
9    Saheed    Tasued   51

In [27]:
Data[Data['Age'] > '20']

Name    School score Age
0    habeeb    Havard    87  23
1  Tajudeen    Oxford    67  25
2     Alabi   Alberta    54  21
4       Ojo  Stanford    76  34
6      Bolu      Lasu    60  90
7     Alake    Unilag    48  40
8    Ishola  Unilorin    34  34
9    Saheed    Tasued    58  51

In [28]:
Data['Nationality'] = 'Usa','Kenya','Togo','Sweden','America','Poland','Germany','London','New sealand','Turkey'

In [29]:
Data

Name    School score  Age  Nationality
0    habeeb    Havard    87   23          Usa
1  Tajudeen    Oxford    67   25        Kenya
2     Alabi   Alberta    54   21         Togo
3      Lola     Kwasu    45   12       Sweden
4       Ojo  Stanford    76   34      America
5     Ahmed  Cabridge   100  100       Poland
6      Bolu      Lasu    60   90      Germany
7     Alake    Unilag    48   40       London
8    Ishola  Unilorin    34   34  New sealand
9    Saheed    Tasued    58   51       Turkey

In [30]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Name         10 non-null     object
 1   School       10 non-null     object
 2   score        10 non-null     object
 3   Age          10 non-null     object
 4   Nationality  10 non-null     object
dtypes: object(5)
memory usage: 528.0+ bytes


In [31]:
Data.set_index('Name')

School score  Age  Nationality
Name                                      
habeeb      Havard    87   23          Usa
Tajudeen    Oxford    67   25        Kenya
Alabi      Alberta    54   21         Togo
Lola         Kwasu    45   12       Sweden
Ojo       Stanford    76   34      America
Ahmed     Cabridge   100  100       Poland
Bolu          Lasu    60   90      Germany
Alake       Unilag    48   40       London
Ishola    Unilorin    34   34  New sealand
Saheed      Tasued    58   51       Turkey

In [35]:
# DO REAESRCH ON THE THE DROP METHOD 

Data_Name_index.drop(columns='Age')

NameError: name 'Data_Name_index' is not defined

# APPLY METHOD 

In [36]:
# Tittle case Application 

Data['Name']=Data['Name'].apply(lambda i: i. title())

In [37]:
Data

Name    School score  Age  Nationality
0    Habeeb    Havard    87   23          Usa
1  Tajudeen    Oxford    67   25        Kenya
2     Alabi   Alberta    54   21         Togo
3      Lola     Kwasu    45   12       Sweden
4       Ojo  Stanford    76   34      America
5     Ahmed  Cabridge   100  100       Poland
6      Bolu      Lasu    60   90      Germany
7     Alake    Unilag    48   40       London
8    Ishola  Unilorin    34   34  New sealand
9    Saheed    Tasued    58   51       Turkey

In [62]:
New_Nationality = ['Sweden','UAE','Turkey','Germany','Russia','Pakistain', 'London', 'Algeria', 'Uk','Scotland']

In [65]:
Data['Nationality'].replace(['Nationality'], ['New_Nationality])

SyntaxError: EOL while scanning string literal (<ipython-input-65-51b5b8e24c70>, line 1)

In [52]:
Data

Name    School score  Age  Nationality
0    Habeeb    Havard    87   23          Usa
1  Tajudeen    Oxford    67   25        Kenya
2     Alabi   Alberta    54   21         Togo
3      Lola     Kwasu    45   12       Sweden
4       Ojo  Stanford    76   34      America
5     Ahmed  Cabridge   100  100       Poland
6      Bolu      Lasu    60   90      Germany
7     Alake    Unilag    48   40       London
8    Ishola  Unilorin    34   34  New sealand
9    Saheed    Tasued    58   51       Turkey

In [ ]:
 = pd.read_csv(r"C:\Users\User\Desktop\AI AND DATA SCIENCE BOOTCAMP\DATA SCIENCE\Jumia_clean Project work.csv")

In [ ]:
Jumia.keys()

In [ ]:
Monday = [
    [1,2,3,4,5,6,7], ['sebi','det','frt','huu','ki','lop','bno'],['garri','eba','fufu','sobo','lopi','boli','teri']
]

In [ ]:
pd.DataFrame(Monday)

In [ ]:
pd.DataFrame(np.array(Monday))

In [ ]:
np.random.randint(0, 50, 20).reshape(10,2)

In [ ]:
Habeeb = pd.DataFrame(np.random.randint(0, 50, 20).reshape(10,2))

In [ ]:
pd.DataFrame(Habeeb, columns = ['a','b','c','d','e','f','g','h','i','j'])

In [ ]:
Jumia

In [ ]:
Jumia[['brand', 'ratings', 'discount']]

In [ ]:
Jumia.info()

In [ ]:
Jumia['brand'].unique()

In [ ]:
Jumia['brand'].value_counts(normalize = True) * 100 

# to find frequent distribution wit the the column/series 

In [ ]:
Jumia['brand'].value_counts(normalize = True) * 100 

# to conveert the distribution to percentage 

In [ ]:
# TO check duplicate value 

Jumia[Jumia.duplicated()]  


# this simple means there are no duplicate values in our data set 

In [ ]:
# to check null value in our data set 

Jumia.isnull().sum()

# DO research on , the best approach to solve data science questions and tips and hacks to know where to start and ho to go about solving issues 