In [31]:
import numpy as np 

In [5]:
np.sum([23, 45, 56, 67, 89, 60])

340

In [6]:
np.std([23, 45, 56, 67, 89, 60])

20.138409955990955

In [7]:
np.median([23, 45, 56, 67, 89, 60])

58.0

In [8]:
np.std([23, 45, 56, 67, 89, 60])

56.666666666666664

In [13]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.random.seed(20)

np.random.randint(200)

99

In [21]:
np.random.rand(3, 4, 4)

array([[[0.0890517 , 0.38334925, 0.41805411, 0.76497233],
        [0.19927802, 0.04904215, 0.67404166, 0.01982033],
        [0.79656607, 0.71550954, 0.29533501, 0.32882246],
        [0.26813417, 0.13655489, 0.37195498, 0.01574185]],

       [[0.34472747, 0.96361998, 0.19585422, 0.96787683],
        [0.08378367, 0.2301467 , 0.16047471, 0.92971001],
        [0.92575366, 0.84710283, 0.45549456, 0.54280335],
        [0.33533569, 0.70095242, 0.63395338, 0.38189399]],

       [[0.89902852, 0.40013986, 0.36056156, 0.82452325],
        [0.04793234, 0.71622117, 0.10118238, 0.96626439],
        [0.1964783 , 0.80990096, 0.29555263, 0.55271805],
        [0.78981762, 0.64608043, 0.47265962, 0.85554434]]])

ARGMAX AND ARGMIX FUNCTION/ SELECTION 

In [24]:
f = ([2, 3, 5, 6, 7, 8, 9])


In [26]:
f

[2, 3, 5, 6, 7, 8, 9]

In [32]:
f < 4

TypeError: '<' not supported between instances of 'list' and 'int'